In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from scipy.stats import chi2_contingency
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, precision_recall_fscore_support
import warnings
import os
import time

In [2]:
print('Program is running....')
print()
start_time = time.time()

Program is running....

In [3]:
a1 = pd.read_csv('casestudy1.csv')
a2 = pd.read_csv('casestudy2.csv')

In [4]:
a1

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.00,0.200,0.800,...,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.00,1.000,0.000,...,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.00,1.000,0.000,...,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.00,0.333,0.667,...,0,0,0,0,0,3,0,2,131,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,3,0,3,1,0,0.333,0.00,1.000,0.000,...,0,2,0,0,0,0,3,1,24,5
51332,51333,4,2,2,0,1,0.000,0.25,0.500,0.500,...,0,2,0,0,0,2,2,0,74,7
51333,51334,2,1,1,1,1,0.500,0.50,0.500,0.500,...,0,2,0,0,0,0,2,0,9,5
51334,51335,2,1,1,0,0,0.000,0.00,0.500,0.500,...,0,2,0,0,0,0,2,0,15,8
51335,51336,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0,0,0,0,0,1,0,0,20,20

In [5]:
a2

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,15,24,23,2,24,24,0,0,0,...,0.0,0.0,0.0,1.661,0,0,ConsumerLoan,ConsumerLoan,650,P4
51332,51333,57,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.520,0,0,others,others,702,P1
51333,51334,32,-99999,-99999,0,-99999,0,0,0,0,...,0.0,1.0,0.0,0.567,0,0,ConsumerLoan,others,661,P3
51334,51335,58,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,1.202,0,0,ConsumerLoan,others,686,P2
51335,51336,74,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,others,others,681,P2

In [6]:
df1 = a1.copy()
df2 = a2.copy()

In [7]:
df1.info

<bound method DataFrame.info of        PROSPECTID  Total_TL  Tot_Closed_TL  Tot_Active_TL  \
0               1         5              4              1
1               2         1              0              1
2               3         8              0              8
3               4         1              0              1
4               5         3              2              1
...           ...       ...            ...            ...
51331       51332         3              0              3
51332       51333         4              2              2
51333       51334         2              1              1
51334       51335         2              1              1
51335       51336         1              0              1

       Total_TL_opened_L6M  Tot_TL_closed_L6M  pct_tl_open_L6M  \
0                        0                  0            0.000
1                        0                  0            0.000
2                        1                  0            0.125
3                        1                  0            1.000
4                        0                  0            0.000
...                    ...                ...              ...
51331                    1                  0            0.333
51332                    0                  1            0.000
51333                    1                  1            0.500
51334                    0                  0            0.000
51335                    0                  0            0.000

       pct_tl_closed_L6M  pct_active_tl  pct_closed_tl  ...  CC_TL  \
0                   0.00          0.200          0.800  ...      0
1                   0.00          1.000          0.000  ...      0
2                   0.00          1.000          0.000  ...      0
3                   0.00          1.000          0.000  ...      0
4                   0.00          0.333          0.667  ...      0
...                  ...            ...            ...  ...    ...
51331               0.00          1.000          0.000  ...      0
51332               0.25          0.500          0.500  ...      0
51333               0.50          0.500          0.500  ...      0
51334               0.00          0.500          0.500  ...      0
51335               0.00          1.000          0.000  ...      0

       Consumer_TL  Gold_TL  Home_TL  PL_TL  Secured_TL  Unsecured_TL  \
0                0        1        0      4           1             4
1                1        0        0      0           0             1
2                6        1        0      0           2             6
3                0        0        0      0           0             1
4                0        0        0      0           3             0
...            ...      ...      ...    ...         ...           ...
51331            2        0        0      0           0             3
51332            2        0        0      0           2             2
51333            2        0        0      0           0             2
51334            2        0        0      0           0             2
51335            0        0        0      0           1             0

       Other_TL  Age_Oldest_TL  Age_Newest_TL
0             0             72             18
1             0              7              7
2             0             47              2
3             1              5              5
4             2            131             32
...         ...            ...            ...
51331         1             24              5
51332         0             74              7
51333         0              9              5
51334         0             15              8
51335         0             20             20

[51336 rows x 26 columns]>

In [8]:
df1.shape

(51336, 26)

In [9]:
# Remove nulls
df1 = df1.loc[df1['Age_Oldest_TL'] != -99999]

In [10]:
columns_to_be_removed = []

for i in df2.columns:
    if df2.loc[df2[i] == -99999].shape[0] > 10000:
        columns_to_be_removed .append(i)

In [11]:
df2 = df2.drop(columns_to_be_removed, axis =1)

In [12]:
for i in df2.columns:
    df2 = df2.loc[ df2[i] != -99999 ]

In [13]:
# Checking common column names
for i in list(df1.columns):
    if i in list(df2.columns):
        print (i)

PROSPECTID

In [14]:
# Merge the two dataframes, inner join so that no nulls are present
df = pd. merge ( df1, df2, how ='inner', left_on = ['PROSPECTID'], right_on = ['PROSPECTID'] )

In [15]:

df.shape

(42064, 79)

In [16]:
df

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,5,4,1,0,0,0.000,0.00,0.200,0.800,...,0.0,0.0,0.000,0.0,1,0,PL,PL,696,P2
1,2,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,8,0,8,1,0,0.125,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,1,0,ConsumerLoan,others,693,P2
3,5,3,2,1,0,0,0.000,0.00,0.333,0.667,...,0.0,0.0,0.000,0.0,0,0,AL,AL,753,P1
4,6,6,5,1,0,0,0.000,0.00,0.167,0.833,...,1.0,0.0,0.429,0.0,1,0,ConsumerLoan,PL,668,P3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42059,51332,3,0,3,1,0,0.333,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,650,P4
42060,51333,4,2,2,0,1,0.000,0.25,0.500,0.500,...,0.0,0.0,0.000,0.0,0,0,others,others,702,P1
42061,51334,2,1,1,1,1,0.500,0.50,0.500,0.500,...,1.0,0.0,1.000,0.0,0,0,ConsumerLoan,others,661,P3
42062,51335,2,1,1,0,0,0.000,0.00,0.500,0.500,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,others,686,P2
42063,51336,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,others,others,681,P2

We will divide the features into - Categorical and Numerical    Treat them seperately

In [17]:
# Check how many columns are categorical
for i in df.columns:
    if df[i].dtype == 'object':
        print(i)

MARITALSTATUS
EDUCATION
GENDER
last_prod_enq2
first_prod_enq2
Approved_Flag

In [18]:
df['MARITALSTATUS'].value_counts()

MARITALSTATUS
Married    30886
Single     11178
Name: count, dtype: int64

In [19]:
df['EDUCATION'].value_counts()

EDUCATION
GRADUATE          14140
12TH              11703
SSC                7241
UNDER GRADUATE     4572
OTHERS             2291
POST-GRADUATE      1898
PROFESSIONAL        219
Name: count, dtype: int64

In [20]:
df['GENDER'].value_counts()

GENDER
M    37345
F     4719
Name: count, dtype: int64

In [21]:
df['Approved_Flag'].value_counts()

Approved_Flag
P2    25452
P3     6440
P4     5264
P1     4908
Name: count, dtype: int64

Are MARITALSTATUS and Approved_Flag associated?

H0 : Not associated
H1 : associated

alpha- significance level, 
strictness level 
generally 5% or 0.05
less risky projects : High alpha
More risky projects : less alpha

Confidence Interval = 1- alpha


Calculate evidence against H0
p-value is calculated using tests.
Eg: t-test, Chi squared test, ANOVA

Compare p value with alpha
if p-value <= alpha:
   reject H0
if p-value > alpha:
   fail to reject H0


Interview ques for DS:
Why not Accept H0?
not have enough evidence.

Chi squared: Cat vs Cat
t - test : Cat vs Num (2 categories)
ANOVA: Cat vs Num (>= 3 categories)

In [22]:
# Chi-square test
for i in ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']:
    chi2, pval, _, _ = chi2_contingency(pd.crosstab(df[i], df['Approved_Flag']))
    print(i, '---', pval)

MARITALSTATUS --- 3.578180861038862e-233
EDUCATION --- 2.6942265249737532e-30
GENDER --- 1.907936100186563e-05
last_prod_enq2 --- 0.0
first_prod_enq2 --- 7.84997610555419e-287

Since all the categorical have p value <= 0.05, we will accept all.

In [23]:
# VIF for numerical columns
numeric_columns = []
for i in df.columns:
    if df[i].dtype != 'object' and i not in ['PROSPECTID','Approved_Flag']:
        numeric_columns.append(i)

Multicollinearity vs Correlation
Multicollinearity : Predictability of each features by other features

Correlation is related to linear relationships between columns.
In convex functions, correlation gives misleading values.

In [24]:
# VIF sequentially check

vif_data = df[numeric_columns]
total_columns = vif_data.shape[1]
columns_to_be_kept = []
column_index = 0



for i in range (0,total_columns):
    
    vif_value = variance_inflation_factor(vif_data, column_index)
    print (column_index,'---',vif_value)
    
    
    if vif_value <= 6:
        columns_to_be_kept.append( numeric_columns[i] )
        column_index = column_index+1
    
    else:
        vif_data = vif_data.drop([ numeric_columns[i] ] , axis=1)

c:\Users\DELL\miniconda3\envs\genai\lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf

c:\Users\DELL\miniconda3\envs\genai\lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf
0 --- 11.320180023967996
0 --- 8.363698035000327
0 --- 6.520647877790928
0 --- 5.149501618212625
1 --- 2.611111040579735

c:\Users\DELL\miniconda3\envs\genai\lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

2 --- inf
2 --- 1788.7926256209232
2 --- 8.601028256477228
2 --- 3.8328007921530785
3 --- 6.0996533816467355
3 --- 5.581352009642762
4 --- 1.9855843530987785

c:\Users\DELL\miniconda3\envs\genai\lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

5 --- inf
5 --- 4.809538302819343
6 --- 23.270628983464636
6 --- 30.595522588100053
6 --- 4.3843464059655854
7 --- 3.064658415523423
8 --- 2.898639771299252
9 --- 4.377876915347322
10 --- 2.2078535836958433
11 --- 4.916914200506864
12 --- 5.214702030064725
13 --- 3.3861625024231476
14 --- 7.840583309478997
14 --- 5.255034641721438

c:\Users\DELL\miniconda3\envs\genai\lib\site-packages\statsmodels\stats\outliers_influence.py:198: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

15 --- inf
15 --- 7.380634506427232
15 --- 1.421005001517573
16 --- 8.083255010190323
16 --- 1.6241227524040114
17 --- 7.257811920140003
17 --- 15.59624383268298
17 --- 1.825857047132431
18 --- 1.5080839450032664
19 --- 2.172088834824578
20 --- 2.623397553527229
21 --- 2.2959970812106167
22 --- 7.360578319196439
22 --- 2.1602387773102554
23 --- 2.8686288267891467
24 --- 6.458218003637277
24 --- 2.8474118865638265
25 --- 4.753198156284083
26 --- 16.22735475594825
26 --- 6.424377256363877
26 --- 8.887080381808687
26 --- 2.3804746142952653
27 --- 8.609513476514548
27 --- 13.06755093547673
27 --- 3.500040056654654
28 --- 1.908795587481377
29 --- 17.006562234161628
29 --- 10.730485153719197
29 --- 2.3538497522950275
30 --- 22.104855915136433
30 --- 2.7971639638512924
31 --- 3.424171203217696
32 --- 10.175021454450935
32 --- 6.408710354561301
32 --- 1.0011511962625619
33 --- 3.069197305397274
34 --- 2.8091261600643724
35 --- 20.249538381980678
35 --- 15.864576541593774
35 --- 1.8331649740532172
36 --- 1.568083990954204
37 --- 1.9307572353811682
38 --- 4.331265056645247
39 --- 9.390334396150173

In [25]:
from scipy.stats import f_oneway

columns_to_be_kept_numerical = []

for i in columns_to_be_kept:
    a = list(df[i])  
    b = list(df['Approved_Flag'])  
    
    group_P1 = [value for value, group in zip(a, b) if group == 'P1']
    group_P2 = [value for value, group in zip(a, b) if group == 'P2']
    group_P3 = [value for value, group in zip(a, b) if group == 'P3']
    group_P4 = [value for value, group in zip(a, b) if group == 'P4']


    f_statistic, p_value = f_oneway(group_P1, group_P2, group_P3, group_P4)

    if p_value <= 0.05:
        columns_to_be_kept_numerical.append(i)

# Label encoding for categorical features
MARITALSTATUS
EDUCATION
GENDER
last_prod_enq2
first_prod_enq2
Approved_Flag

In [26]:
# listing all the final features
features = columns_to_be_kept_numerical + ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']
df = df[features + ['Approved_Flag']]

In [27]:
df['MARITALSTATUS'].unique()    
df['EDUCATION'].unique()
df['GENDER'].unique()
df['last_prod_enq2'].unique()
df['first_prod_enq2'].unique()

array(['PL', 'ConsumerLoan', 'others', 'AL', 'HL', 'CC'], dtype=object)

In [28]:
df['EDUCATION'].unique()

array(['12TH', 'GRADUATE', 'SSC', 'POST-GRADUATE', 'UNDER GRADUATE',
       'OTHERS', 'PROFESSIONAL'], dtype=object)

Ordinal feature -- EDUCATION
 SSC            : 1
 12TH           : 2
 GRADUATE       : 3
 UNDER GRADUATE : 3
 POST-GRADUATE  : 4
 OTHERS         : 1
 PROFESSIONAL   : 3

In [29]:
df.loc[df['EDUCATION'] == 'SSC',['EDUCATION']]              = 1
df.loc[df['EDUCATION'] == '12TH',['EDUCATION']]             = 2
df.loc[df['EDUCATION'] == 'GRADUATE',['EDUCATION']]         = 3
df.loc[df['EDUCATION'] == 'UNDER GRADUATE',['EDUCATION']]   = 3
df.loc[df['EDUCATION'] == 'POST-GRADUATE',['EDUCATION']]    = 4
df.loc[df['EDUCATION'] == 'OTHERS',['EDUCATION']]           = 1
df.loc[df['EDUCATION'] == 'PROFESSIONAL',['EDUCATION']]     = 3

In [30]:
df['EDUCATION'].value_counts()

EDUCATION
3    18931
2    11703
1     9532
4     1898
Name: count, dtype: int64

In [31]:
df['EDUCATION'] = df['EDUCATION'].astype(int)

C:\Users\DELL\AppData\Local\Temp\ipykernel_12016\2323562331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['EDUCATION'] = df['EDUCATION'].astype(int)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 43 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   pct_tl_open_L6M            42064 non-null  float64
 1   pct_tl_closed_L6M          42064 non-null  float64
 2   Tot_TL_closed_L12M         42064 non-null  int64
 3   pct_tl_closed_L12M         42064 non-null  float64
 4   Tot_Missed_Pmnt            42064 non-null  int64
 5   CC_TL                      42064 non-null  int64
 6   Home_TL                    42064 non-null  int64
 7   PL_TL                      42064 non-null  int64
 8   Secured_TL                 42064 non-null  int64
 9   Unsecured_TL               42064 non-null  int64
 10  Other_TL                   42064 non-null  int64
 11  Age_Oldest_TL              42064 non-null  int64
 12  Age_Newest_TL              42064 non-null  int64
 13  time_since_recent_payment  42064 non-null  int64
 14  max_recent_level_of_deliq  42064 non-null  int64
 15  num_deliq_6_12mts          42064 non-null  int64
 16  num_times_60p_dpd          42064 non-null  int64
 17  num_std_12mts              42064 non-null  int64
 18  num_sub                    42064 non-null  int64
 19  num_sub_6mts               42064 non-null  int64
 20  num_sub_12mts              42064 non-null  int64
 21  num_dbt                    42064 non-null  int64
 22  num_dbt_12mts              42064 non-null  int64
 23  num_lss                    42064 non-null  int64
 24  recent_level_of_deliq      42064 non-null  int64
 25  CC_enq_L12m                42064 non-null  int64
 26  PL_enq_L12m                42064 non-null  int64
 27  time_since_recent_enq      42064 non-null  int64
 28  enq_L3m                    42064 non-null  int64
 29  NETMONTHLYINCOME           42064 non-null  int64
 30  Time_With_Curr_Empr        42064 non-null  int64
 31  CC_Flag                    42064 non-null  int64
 32  PL_Flag                    42064 non-null  int64
 33  pct_PL_enq_L6m_of_ever     42064 non-null  float64
 34  pct_CC_enq_L6m_of_ever     42064 non-null  float64
 35  HL_Flag                    42064 non-null  int64
 36  GL_Flag                    42064 non-null  int64
 37  MARITALSTATUS              42064 non-null  object
 38  EDUCATION                  42064 non-null  int32
 39  GENDER                     42064 non-null  object
 40  last_prod_enq2             42064 non-null  object
 41  first_prod_enq2            42064 non-null  object
 42  Approved_Flag              42064 non-null  object
dtypes: float64(5), int32(1), int64(32), object(5)
memory usage: 13.6+ MB

In [33]:
df_encoded = pd.get_dummies(df, columns=['MARITALSTATUS','GENDER', 'last_prod_enq2' ,'first_prod_enq2'])

In [34]:
df_encoded.info()
k = df_encoded.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 55 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   pct_tl_open_L6M               42064 non-null  float64
 1   pct_tl_closed_L6M             42064 non-null  float64
 2   Tot_TL_closed_L12M            42064 non-null  int64
 3   pct_tl_closed_L12M            42064 non-null  float64
 4   Tot_Missed_Pmnt               42064 non-null  int64
 5   CC_TL                         42064 non-null  int64
 6   Home_TL                       42064 non-null  int64
 7   PL_TL                         42064 non-null  int64
 8   Secured_TL                    42064 non-null  int64
 9   Unsecured_TL                  42064 non-null  int64
 10  Other_TL                      42064 non-null  int64
 11  Age_Oldest_TL                 42064 non-null  int64
 12  Age_Newest_TL                 42064 non-null  int64
 13  time_since_recent_payment     42064 non-null  int64
 14  max_recent_level_of_deliq     42064 non-null  int64
 15  num_deliq_6_12mts             42064 non-null  int64
 16  num_times_60p_dpd             42064 non-null  int64
 17  num_std_12mts                 42064 non-null  int64
 18  num_sub                       42064 non-null  int64
 19  num_sub_6mts                  42064 non-null  int64
 20  num_sub_12mts                 42064 non-null  int64
 21  num_dbt                       42064 non-null  int64
 22  num_dbt_12mts                 42064 non-null  int64
 23  num_lss                       42064 non-null  int64
 24  recent_level_of_deliq         42064 non-null  int64
 25  CC_enq_L12m                   42064 non-null  int64
 26  PL_enq_L12m                   42064 non-null  int64
 27  time_since_recent_enq         42064 non-null  int64
 28  enq_L3m                       42064 non-null  int64
 29  NETMONTHLYINCOME              42064 non-null  int64
 30  Time_With_Curr_Empr           42064 non-null  int64
 31  CC_Flag                       42064 non-null  int64
 32  PL_Flag                       42064 non-null  int64
 33  pct_PL_enq_L6m_of_ever        42064 non-null  float64
 34  pct_CC_enq_L6m_of_ever        42064 non-null  float64
 35  HL_Flag                       42064 non-null  int64
 36  GL_Flag                       42064 non-null  int64
 37  EDUCATION                     42064 non-null  int32
 38  Approved_Flag                 42064 non-null  object
 39  MARITALSTATUS_Married         42064 non-null  bool
 40  MARITALSTATUS_Single          42064 non-null  bool
 41  GENDER_F                      42064 non-null  bool
 42  GENDER_M                      42064 non-null  bool
 43  last_prod_enq2_AL             42064 non-null  bool
 44  last_prod_enq2_CC             42064 non-null  bool
 45  last_prod_enq2_ConsumerLoan   42064 non-null  bool
 46  last_prod_enq2_HL             42064 non-null  bool
 47  last_prod_enq2_PL             42064 non-null  bool
 48  last_prod_enq2_others         42064 non-null  bool
 49  first_prod_enq2_AL            42064 non-null  bool
 50  first_prod_enq2_CC            42064 non-null  bool
 51  first_prod_enq2_ConsumerLoan  42064 non-null  bool
 52  first_prod_enq2_HL            42064 non-null  bool
 53  first_prod_enq2_PL            42064 non-null  bool
 54  first_prod_enq2_others        42064 non-null  bool
dtypes: bool(16), float64(5), int32(1), int64(32), object(1)
memory usage: 13.0+ MB

Machine Learning Model Fitting:

In [35]:
# 1. Random Forest

y = df_encoded['Approved_Flag']
x = df_encoded.drop(['Approved_Flag'], axis = 1)

In [36]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [37]:
rf_classifier = RandomForestClassifier(n_estimators=200,random_state=42)

In [38]:
rf_classifier.fit(x_train,y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [39]:
y_pred = rf_classifier.predict(x_test)

In [40]:
accuracy = accuracy_score(y_test,y_pred)
print()
print(f'Accuracy: {accuracy}')
print()
precision,recall,f1_score, _ = precision_recall_fscore_support(y_test,y_pred)

for i, v in enumerate(['p1','p2','p3','p4']):
    print(f"class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.7636990372043266

class p1:
Precision: 0.8370457209847597
Recall: 0.7041420118343196
F1 Score: 0.7648634172469203

class p2:
Precision: 0.7957519116397621
Recall: 0.9282457879088206
F1 Score: 0.8569075937785909

class p3:
Precision: 0.4423380726698262
Recall: 0.21132075471698114
F1 Score: 0.28600612870275793

class p4:
Precision: 0.7178502879078695
Recall: 0.7269193391642371
F1 Score: 0.7223563495895703

F1 score = 2 * p * r / (p + r)

In [41]:
# 2. xgboost

In [42]:
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder

In [43]:
xgb_classifier = xgb.XGBClassifier(objective='multi:softmax',num_class = 4)

In [44]:
y = df_encoded['Approved_Flag']
x = df_encoded.drop(['Approved_Flag'], axis = 1)

In [45]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

In [46]:
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)

In [47]:
xgb_classifier.fit(x_train, y_train)
y_pred = xgb_classifier.predict(x_test)

In [48]:
accuracy = accuracy_score(y_test, y_pred)
print ()
print(f'Accuracy: {accuracy:.2f}')
print ()

precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.78

Class p1:
Precision: 0.823906083244397
Recall: 0.7613412228796844
F1 Score: 0.7913890312660173

Class p2:
Precision: 0.8255418233924413
Recall: 0.913577799801784
F1 Score: 0.8673315769665036

Class p3:
Precision: 0.4756380510440835
Recall: 0.30943396226415093
F1 Score: 0.3749428440786465

Class p4:
Precision: 0.7342386032977691
Recall: 0.7356656948493683
F1 Score: 0.7349514563106796

In [49]:
# 3. Decision Tree

In [50]:
from sklearn.tree import DecisionTreeClassifier


y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


dt_model = DecisionTreeClassifier(max_depth=20, min_samples_split=10)
dt_model.fit(x_train, y_train)
y_pred = dt_model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print ()
print(f"Accuracy: {accuracy:.2f}")
print ()

precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.71

Class p1:
Precision: 0.7168141592920354
Recall: 0.7189349112426036
F1 Score: 0.7178729689807976

Class p2:
Precision: 0.8081259720062208
Recall: 0.82398414271556
F1 Score: 0.8159780155069192

Class p3:
Precision: 0.3450199203187251
Recall: 0.3267924528301887
F1 Score: 0.33565891472868215

Class p4:
Precision: 0.6469408224674023
Recall: 0.6268221574344023
F1 Score: 0.6367226061204343

In [51]:
df_encoded['Approved_Flag']

0        P2
1        P2
2        P2
3        P1
4        P3
         ..
42059    P4
42060    P1
42061    P3
42062    P2
42063    P2
Name: Approved_Flag, Length: 42064, dtype: object

In [52]:
df_encoded['Approved_Flag'].value_counts()

Approved_Flag
P2    25452
P3     6440
P4     5264
P1     4908
Name: count, dtype: int64

In [53]:
# # Hyperparameter tuning for xgboost (Used in the session)

# # Define the hyperparameter grid
param_grid = {
  'colsample_bytree': [0.1, 0.3, 0.5, 0.7, 0.9],
   'learning_rate'   : [0.001, 0.01, 0.1, 1],
   'max_depth'       : [3, 5, 8, 10],
   'alpha'           : [1, 10, 100],
   'n_estimators'    : [10,50,100]
 }

index = 0

answers_grid = {
     'combination'       :[],
     'train_Accuracy'    :[],
     'test_Accuracy'     :[],
     'colsample_bytree'  :[],
     'learning_rate'     :[],
     'max_depth'         :[],
     'alpha'             :[],
     'n_estimators'      :[]

     }


# # Loop through each combination of hyperparameters
for colsample_bytree in param_grid['colsample_bytree']:
   for learning_rate in param_grid['learning_rate']:
     for max_depth in param_grid['max_depth']:
       for alpha in param_grid['alpha']:
           for n_estimators in param_grid['n_estimators']:
             
               index = index + 1
             
               # Define and train the XGBoost model
               model = xgb.XGBClassifier(objective='multi:softmax',  
                                        num_class=4,
                                        colsample_bytree = colsample_bytree,
                                        learning_rate = learning_rate,
                                        max_depth = max_depth,
                                        alpha = alpha,
                                        n_estimators = n_estimators)
               
       
                     
               y = df_encoded['Approved_Flag']
               x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )

               label_encoder = LabelEncoder()
               y_encoded = label_encoder.fit_transform(y)


               x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)


               model.fit(x_train, y_train)
  

       
#               # Predict on training and testing sets
               y_pred_train = model.predict(x_train)
               y_pred_test = model.predict(x_test)
       
       
#               # Calculate train and test results
              
               train_accuracy =  accuracy_score (y_train, y_pred_train)
               test_accuracy  =  accuracy_score (y_test , y_pred_test)
              
              
       
#               # Include into the lists
               answers_grid ['combination']   .append(index)
               answers_grid ['train_Accuracy']    .append(train_accuracy)
               answers_grid ['test_Accuracy']     .append(test_accuracy)
               answers_grid ['colsample_bytree']   .append(colsample_bytree)
               answers_grid ['learning_rate']      .append(learning_rate)
               answers_grid ['max_depth']          .append(max_depth)
               answers_grid ['alpha']              .append(alpha)
               answers_grid ['n_estimators']       .append(n_estimators)
       
       
#               # Print results for this combination
               print(f"Combination {index}")
               print(f"colsample_bytree: {colsample_bytree}, learning_rate: {learning_rate}, max_depth: {max_depth}, alpha: {alpha}, n_estimators: {n_estimators}")
               print(f"Train Accuracy: {train_accuracy:.2f}")
               print(f"Test Accuracy : {test_accuracy :.2f}")
               print("-" * 30)

Combination 1
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 3, alpha: 1, n_estimators: 10
Train Accuracy: 0.61
Test Accuracy : 0.61
------------------------------
Combination 2
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 3, alpha: 1, n_estimators: 50
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 3
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 3, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 4
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 3, alpha: 10, n_estimators: 10
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 5
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 3, alpha: 10, n_estimators: 50
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 6
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 3, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 7
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 3, alpha: 100, n_estimators: 10
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 8
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 3, alpha: 100, n_estimators: 50
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 9
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 3, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 10
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 5, alpha: 1, n_estimators: 10
Train Accuracy: 0.62
Test Accuracy : 0.61
------------------------------
Combination 11
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 5, alpha: 1, n_estimators: 50
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 12
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 5, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 13
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 5, alpha: 10, n_estimators: 10
Train Accuracy: 0.61
Test Accuracy : 0.61
------------------------------
Combination 14
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 5, alpha: 10, n_estimators: 50
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 15
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 5, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 16
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 5, alpha: 100, n_estimators: 10
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 17
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 5, alpha: 100, n_estimators: 50
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 18
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 5, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 19
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 8, alpha: 1, n_estimators: 10
Train Accuracy: 0.62
Test Accuracy : 0.61
------------------------------
Combination 20
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 8, alpha: 1, n_estimators: 50
Train Accuracy: 0.61
Test Accuracy : 0.61
------------------------------
Combination 21
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 8, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 22
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 8, alpha: 10, n_estimators: 10
Train Accuracy: 0.61
Test Accuracy : 0.61
------------------------------
Combination 23
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 8, alpha: 10, n_estimators: 50
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 24
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 8, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------

KeyboardInterrupt:

In [54]:
#after finetuning:
model = xgb.XGBClassifier(objective='multi:softmax', num_class=4, colsample_bytree=0.9,learning_rate=1,max_depth=3,alpha=10,n_estimators=100)

In [55]:
# Predict the unseen data
a3 = pd.read_excel('Unseen_Dataset.xlsx')

In [56]:
cols_in_df = list(df.columns)
cols_in_df.pop(42)

'Approved_Flag'

In [57]:
df_unseen = a3 [cols_in_df]

In [58]:
df_unseen['MARITALSTATUS'].unique()
df_unseen['EDUCATION'].unique()
df_unseen['GENDER'].unique()
df_unseen['last_prod_enq2'].unique()
df_unseen['first_prod_enq2'].unique()

array(['PL', 'ConsumerLoan', 'others', 'AL', 'HL', 'CC'], dtype=object)

In [59]:
df_unseen.loc[df['EDUCATION'] == 'SSC',['EDUCATION']]              = 1
df_unseen.loc[df['EDUCATION'] == '12TH',['EDUCATION']]             = 2
df_unseen.loc[df['EDUCATION'] == 'GRADUATE',['EDUCATION']]         = 3
df_unseen.loc[df['EDUCATION'] == 'UNDER GRADUATE',['EDUCATION']]   = 3
df_unseen.loc[df['EDUCATION'] == 'POST-GRADUATE',['EDUCATION']]    = 4
df_unseen.loc[df['EDUCATION'] == 'OTHERS',['EDUCATION']]           = 1
df_unseen.loc[df['EDUCATION'] == 'PROFESSIONAL',['EDUCATION']]     = 3

In [60]:
df_encoded_unseen = pd.get_dummies(df_unseen, columns=['MARITALSTATUS','GENDER', 'last_prod_enq2' ,'first_prod_enq2'])

In [61]:
df_encoded_unseen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 54 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   pct_tl_open_L6M               100 non-null    float64
 1   pct_tl_closed_L6M             100 non-null    float64
 2   Tot_TL_closed_L12M            100 non-null    int64
 3   pct_tl_closed_L12M            100 non-null    float64
 4   Tot_Missed_Pmnt               100 non-null    int64
 5   CC_TL                         100 non-null    int64
 6   Home_TL                       100 non-null    int64
 7   PL_TL                         100 non-null    int64
 8   Secured_TL                    100 non-null    int64
 9   Unsecured_TL                  100 non-null    int64
 10  Other_TL                      100 non-null    int64
 11  Age_Oldest_TL                 100 non-null    int64
 12  Age_Newest_TL                 100 non-null    int64
 13  time_since_recent_payment     100 non-null    int64
 14  max_recent_level_of_deliq     100 non-null    int64
 15  num_deliq_6_12mts             100 non-null    int64
 16  num_times_60p_dpd             100 non-null    int64
 17  num_std_12mts                 100 non-null    int64
 18  num_sub                       100 non-null    int64
 19  num_sub_6mts                  100 non-null    int64
 20  num_sub_12mts                 100 non-null    int64
 21  num_dbt                       100 non-null    int64
 22  num_dbt_12mts                 100 non-null    int64
 23  num_lss                       100 non-null    int64
 24  recent_level_of_deliq         100 non-null    int64
 25  CC_enq_L12m                   100 non-null    int64
 26  PL_enq_L12m                   100 non-null    int64
 27  time_since_recent_enq         100 non-null    int64
 28  enq_L3m                       100 non-null    int64
 29  NETMONTHLYINCOME              100 non-null    int64
 30  Time_With_Curr_Empr           100 non-null    int64
 31  CC_Flag                       100 non-null    int64
 32  PL_Flag                       100 non-null    int64
 33  pct_PL_enq_L6m_of_ever        100 non-null    float64
 34  pct_CC_enq_L6m_of_ever        100 non-null    float64
 35  HL_Flag                       100 non-null    int64
 36  GL_Flag                       100 non-null    int64
 37  EDUCATION                     100 non-null    object
 38  MARITALSTATUS_Married         100 non-null    bool
 39  MARITALSTATUS_Single          100 non-null    bool
 40  GENDER_F                      100 non-null    bool
 41  GENDER_M                      100 non-null    bool
 42  last_prod_enq2_AL             100 non-null    bool
 43  last_prod_enq2_CC             100 non-null    bool
 44  last_prod_enq2_ConsumerLoan   100 non-null    bool
 45  last_prod_enq2_HL             100 non-null    bool
 46  last_prod_enq2_PL             100 non-null    bool
 47  last_prod_enq2_others         100 non-null    bool
 48  first_prod_enq2_AL            100 non-null    bool
 49  first_prod_enq2_CC            100 non-null    bool
 50  first_prod_enq2_ConsumerLoan  100 non-null    bool
 51  first_prod_enq2_HL            100 non-null    bool
 52  first_prod_enq2_PL            100 non-null    bool
 53  first_prod_enq2_others        100 non-null    bool
dtypes: bool(16), float64(5), int64(32), object(1)
memory usage: 31.4+ KB

In [62]:
k = df_encoded_unseen.describe()